language: node_js

cache: npm

install:
  - NODE_ENV=dev npm install

before_script:
  - npm run lint

script:
  - npm test

before_deploy:
  - npm run build:prod

deploy:
  provider: npm
  email: kelly@akirix.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
