language: node_js
version: 1.0

cache: npm

install:
  - NODE_ENV=dev npm install

before_script:
  - npm run lint

script:
  - npm test

before_deploy:
  - npm run build:prod
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
